name: myproject_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy==1.26.4
    - opencv-python==4.10.0.82
    - setuptools==70.0.0
    - imutils
    - mediapipe
    - dlib==19.24.4
    - scipy
    - keras
    - tensorflow